/*
 * This file is part of Breezy Weather.
 *
 * Breezy Weather is free software: you can redistribute it and/or modify it
 * under the terms of the GNU Lesser General Public License as published by the
 * Free Software Foundation, version 3 of the License.
 *
 * Breezy Weather is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
 * or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public
 * License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with Breezy Weather. If not, see <https://www.gnu.org/licenses/>.
 */

package com.liveweatherwallpaperapp.common.update

import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import okhttp3.OkHttpClient
import okhttp3.Request
import org.json.JSONObject
import java.util.concurrent.TimeUnit

/**
 * The latest GitHub release's notes for the "what's new" screen shown after an app update.
 * The body text is whatever `scripts/release.ps1` published — auto-generated by
 * `gh release create --generate-notes` (a commit/PR list), since that's what's actually
 * available on GitHub for a release, as opposed to the short highlight blurb typed at release
 * time, which today only goes out via the FCM "new version available" push notification.
 */
class GithubReleaseNotesSource(
    private val client: OkHttpClient = defaultClient(),
) {
    data class ReleaseNotes(val tagName: String, val body: String, val htmlUrl: String)

    suspend fun getLatest(): ReleaseNotes? {
        return withContext(Dispatchers.IO) {
            try {
                val request = Request.Builder()
                    .url(LATEST_RELEASE_URL)
                    .header("Accept", "application/vnd.github+json")
                    .build()
                client.newCall(request).execute().use { response ->
                    if (!response.isSuccessful) return@use null
                    val json = JSONObject(response.body.string())
                    ReleaseNotes(
                        tagName = json.optString("tag_name"),
                        body = json.optString("body"),
                        htmlUrl = json.optString("html_url")
                    )
                }
            } catch (e: Throwable) {
                null
            }
        }
    }

    companion object {
        private const val LATEST_RELEASE_URL =
            "https://api.github.com/repos/strammermax/breezy-weather/releases/latest"

        private fun defaultClient(): OkHttpClient = OkHttpClient.Builder()
            .connectTimeout(10, TimeUnit.SECONDS)
            .readTimeout(10, TimeUnit.SECONDS)
            .build()
    }
}
